language: python
python:
  - "3.5"
# command to install dependencies
before_install: "sudo apt-get -qq update"
"sudo apt-get install build-essential cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev python3-numpy python3-matplotlib python3.5-dev"
"sudo cp /usr/include/x86_64-linux-gnu/python3.5m/pyconfig.h /usr/include/python3.5m/"
"mkdir OpenCV-tmp"
"cd OpenCV-tmp"
"git clone https://github.com/Itseez/opencv.git"
"cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ../opencv-3"
"make"
"sudo make install"
install: "pip install -r requirements.txt"
# command to run tests
# script: pytest
